apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: retail
  description: The Retail API
spec:
  type: openapi
  lifecycle: production
  owner: cory.foy@betterment.com
  definition:
    $text: http://localhost:64246/retail.json
